### ISSUE TITLE
Create an automated calendar integration

### ISSUE THREAD

**Issue by theecrit** [openoakland/openoakland.org#109]
## Description
Our /calendar page only has static content that needs to be updated manually, resulting in it frequently being out-of-date. The format of the info is also not calendar-friendly/conducive to easily spotting relevant event info.

## Recommended solution
- Embed the "Our Next Meeting" include currently on the home page on the /calendar page, too.
- Bonus points: Underneath that, embed the month-view of the OO Google Calendar (assuming we have one) into the page, so we only have to update the calendar and not the website.

### If you are working on this issue, consider the following ongoing issues:
- [ ] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

**Comment by theecrit** [comment]
FWIW, I now have access to the OpenOakland Google cal.

**Comment by ckingbailey** [comment]
@Hedera found some Jekyll plugins for, I believe 
(Is GH gonna let me tag her here if she’s not in this org?)
