### ISSUE TITLE
Add OO Style Guide to /resources

### ISSUE THREAD

**Issue by theecrit** [openoakland/openoakland.org#124]
## Description
Currently, the OpenOakland Style Guide lives in a shared Google Drive that makes it difficult to access for those not in the know.

## Proposed solution
Add a link to the Style Guide (https://docs.google.com/document/d/1SvhwrQcu4mNMS05zE4AIXA8zsc7qpUeWVA9GvgiZaHo/edit?usp=sharing) to the "Tools for running your OpenOakland project" section on the /resources page.

### Impacted files

- /src > resources.md
- https://docs.google.com/document/d/1SvhwrQcu4mNMS05zE4AIXA8zsc7qpUeWVA9GvgiZaHo/edit?usp=sharing

#### If you are working on this issue, consider the following ongoing issues:
- [ ] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

**Comment by robdodson** [comment]
🙌 I can take this one
