### ISSUE TITLE
[Update] Replace mentions of #leadership with #oo-leadership

### ISSUE THREAD

**Issue by theecrit** [openoakland/openoakland.org#125]
## Description
We recently updated the Slack channel naming conventions and need to replace old channel mentions of #leadership (and any other random channels referenced throughout the site) with the new channel name: #oo-leadership

## Files impacted
There may be more! Whoever picks up this issue should do a review of all copy on the site to be sure I caught them all (a find replace on the files themselves may be the easiest approach):

- https://openoakland.org/projects
- https://openoakland.org/about-us/

#### If you are working on this issue, consider the following ongoing issues:
- [ ] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

**Comment by robdodson** [comment]
I'm happy to work on this one.
