### ISSUE TITLE
Add filter to /projects page

### ISSUE THREAD

**Issue by theecrit** [openoakland/openoakland.org#126]
## Description
Currently, all projects are essentially listed in one long column, making it hard to identify relevant projects. We'd like to add some method of organization/filtering to enable readers to identify projects that best fit their interests.

## Potential solution
See: https://github.com/openoakland/openoakland.org/issues/55#issuecomment-721514034

### Taxonomy
Any filters will require a tagging taxonomy. Basic taxonomies currently in use (in Hack Night intro deck; note lowercase capitalization style) includes:

**Type**
- openoakland
- open data
- community services

**Topic**
- arts
- education
- environment
- budgeting
- campaign finance
- city council
- food security

A third taxonomy would be the one already in use in the page nav, which should probably be updated to:

**Status**
- Ongoing
- Active
- Dormant
- Complete
- Decommissioned

While taxonomies could stand to be revisited, this is not within the scope of this issue.

### Layout and behavior

- Recommendation: default view to "Active" projects, rather than all.

#### If you are working on this issue, consider the following ongoing issues:
- [ ] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

**Comment by robdodson** [comment]
I have a rough prototype of this feature in a branch (https://github.com/robdodson/openoakland.org/tree/feat/project-filter)

Here's a quick video of it in action:

https://user-images.githubusercontent.com/1066253/104076244-5cf90780-51ca-11eb-85ba-4f58e4caa047.mp4

It should be able to support multiple buttons for different tag groups. Still a fair amount of js and css clean up to do, but it's coming along :)
