### ISSUE TITLE
Add in our basic branding content - colors + logo

### ISSUE THREAD

**Issue by anlawyer** [openoakland/openoakland.org#13]

**Comment by anlawyer** [comment]
Look into a different Jekyll theme? Larger design discussions to be had here...

**Comment by TangoYankee** [comment]
Could we also have a link to the branding document, in either `Press` or `Resources`?

**Comment by tdooner** [comment]
@TangoYankee Do you mean this one? https://docs.google.com/document/d/1SvhwrQcu4mNMS05zE4AIXA8zsc7qpUeWVA9GvgiZaHo/edit

**Comment by TangoYankee** [comment]
> @TangoYankee Do you mean this one? https://docs.google.com/document/d/1SvhwrQcu4mNMS05zE4AIXA8zsc7qpUeWVA9GvgiZaHo/edit

That's the one!
