### ISSUE TITLE
Re-add the correct images in the correct places

### ISSUE THREAD

**Issue by anlawyer** [openoakland/openoakland.org#14]
Images currently in the WP site:
- [x] meetup, "OO on Slack" images on the landing page
- [x] about us page - collage
- [x] steering committee members
- [x] project screenshots

PDFs:
- [ ] 6 Steps to Leading a Project

**Comment by anlawyer** [comment]
There's also PDFs in a few places that need to be downloaded and added back.

**Comment by ckingbailey** [comment]
resolved by #22
