### ISSUE TITLE
slack channel returning "no perms" on attempt to join

### ISSUE THREAD

**Issue by jaguila** [openoakland/openoakland.org#159]
Sorry I was not sure how else to contact someone concerning this

**Comment by theecrit** [comment]
Hey there! We just discovered this bug tonight; sorry about the issues. Can you send me your email (you can email me at jess@openoakland.org), and I'll get you into the Slack space asap.

**Comment by theecrit** [comment]
The Slackin integration we're using appears to be broken: https://github.com/rauchg/slackin/issues

It also seems that Slack has changed their signup options. Whereas you used to be able allow people to self-join, that's no longer the case. We'll need a new option.

**Comment by theecrit** [comment]
New invite link to be added: https://join.slack.com/t/openoakland/shared_invite/zt-n4d7tx2t-UVIN7a769e4oc9j7PgM3HA
