### ISSUE TITLE
Broken links found

### ISSUE THREAD

**Issue by nydame** [openoakland/openoakland.org#188]
## What are you submitting?
Place an x in the appropriate bracket:

- [x] Bug (something's broken)
- [ ] Feature request or improvement
- [ ] Content update
- [ ] Question
- [ ] Other

## Description
Describe the issue, question, or request in as much detail as you can.
**Someone found 4 broken issues on the OO website** but opened the issue with Open Budget Oakland. I have closed the issue, but it can still be read here: https://github.com/openoakland/openbudgetoakland/issues/190

### Bug reports
Please add the following...

#### Steps you took when encountering the bug
1. **The person who submitted the issue used https://deadlinkchecker.com.**
2.
3.

#### What you expected to happen
Add your answer.

#### The operating system and browser versions you were using
- Operating system:
- Browser:

**Comment by theecrit** [comment]
@nydame @aenygma Thank you! Will get these addressed in the next content update.
