### ISSUE TITLE
design issues blocking launch

### ISSUE THREAD

**Issue by tdooner** [openoakland/openoakland.org#28]
# layout (header)
- [x] move "press" link to footer
- [x] move "steering committee" content to "about us" page
- [x] move "make a donation" link to the right side of the nav, and change text to "donate"
- [x] use horizontal variant of logo and make it 280px wide or so

# calendar page
- [x] add new dates and remove old dates
- [x] link to our meetup and eventbrite as well

# donate page
- [x] make the button look like a button

# project page
- [x] move CUTGroup and OpenOasis into inactive projects

# homepage
- [ ] update the copy to alison's notebook (todo: write the actual copy)
- [x] add photo from a recent event

**Comment by anlawyer** [comment]
🚀 Website LAUNCHED on July 21st, 2019 🚀 
Thank you @tdooner! :shipit:
