### ISSUE TITLE
Update landing/home page content

### ISSUE THREAD

**Issue by anlawyer** [openoakland/openoakland.org#39]

**Comment by Deckert** [comment]
I do believe the Home page could benefit from some fresh content (ideally as part of a larger effort to grow the functionality of the site, particularly in light of our evolving communication needs during the pandemic). 

In the meantime I'd like to use this open issue to address some smaller, immediate changes to the Home page:

**Main objective:**

- Update the language of the "Our Next Meeting" section to reflect our current reality and include the url (shortlink) to our Zoom meetings.

**Secondary objectives (optional):**

- Replace lead image with something newer, more representative, or at least a higher-contrast version of that photo?
- Remove "get an invite to"
- Make Slack info more prominent?
- Add announcement section?
