### ISSUE TITLE
make a nice 404 page

### ISSUE THREAD

**Issue by ckingbailey** [openoakland/openoakland.org#45]
404 page is a little broken-looking. It looks like the header and footer are present but not getting styled. It'd be nice to bring the design in line with the rest of the site.

![Screen Shot 2019-08-21 at 10 58 24 AM](https://user-images.githubusercontent.com/20404311/63457008-f91f4480-c404-11e9-9ef6-7b3fd554cc4a.png)

**Comment by anlawyer** [comment]
I was going to make this issue too. Thanks @ckingbailey!

**Comment by TangoYankee** [comment]
I think its a configuration, rather than styling issue. I think I might have something. If it pans out, I'll make a PR.
