### ISSUE TITLE
Make sure the donate button works

### ISSUE THREAD

**Issue by adborden** [openoakland/openoakland.org#6]

**Comment by anlawyer** [comment]
![donate](https://user-images.githubusercontent.com/28023047/56938623-cd73f980-6ab7-11e9-94a2-1c0c6fe5dfd6.gif)

@adborden what do you think? I think the comic sans really pulls it all together, and where would we be without `<marquee behavior="alternate">`?

> (For complete transparency, this is a joke.)

**Comment by adborden** [comment]
Looks like the button is working hard! :sunglasses:

**Comment by anlawyer** [comment]
The donate link works, the button just needs some styling.
