### ISSUE TITLE
Update Steering Committee to 2020's Committee 

### ISSUE THREAD

**Issue by anlawyer** [openoakland/openoakland.org#77]
Let's update the steering committee page to this year's team! The file to be updated is `steering-committee.html`.

**Comment by theecrit** [comment]
@anlawyer Can you confirm the following? 

Communications Lead: Lydia Kats & Thomas Deckert
Community Organizer: Gaurav Kulkarni
Hack Night Lead: Colin King-Bailey
Treasurer/Recorder: Andrew Tom
Ombudsperson: Ronald Pineda (do we have one more?)

**Comment by mikeubell** [comment]
Mary Yee is the second ombudsperson.  Also Thomas is Chair of the steering committee

**Comment by Deckert** [comment]
I just submitted a PR to resolve this issue.

**Comment by theecrit** [comment]
Beat me to it. 

And thanks, @mikeubell.

:)

**Comment by theecrit** [comment]
Fixed by #82; can someone either close this issue or grant me repo permissions to do so? Thanks!
