### ISSUE TITLE
Revise About Us page to make org-specific details easier to scan

### ISSUE THREAD

**Issue by theecrit** [openoakland/openoakland.org#84]
### Description
As an OpenOakland member and general member of the public, I'd like to be able to quickly understand several things when visiting the About Us page on the website:

- The financial and legal status of OpenOakland (fiscal and operating relationship to CfA)
- Governance model and team
- Governance process and how to participate

Currently, these details are all combined into a few paragraphs of text and are difficult to quickly scan and understand.

### Potential solution

- [ ] Create separate sections marked by `h2`s on the page for:
 - Overview
 - Participation
 - Governance structure
 - Steering committee
 - Values and Code of Conduct (these are currently in the footer but given their importance it's worth elevating to the main body of the page)

**Comment by mikeubell** [comment]
OpenOakland is not a 501c3 corporation. We are an association (not sure if
that is the exact legal term) with Code For America as our fiscal sponsor.

**Comment by theecrit** [comment]
@mikeubell Nope, an association is something different — on closer reading, I see we're fiscally sponsored project of CfA. I've revised the issue to better reflect the need! Thanks. :)
