### ISSUE TITLE
Add upcoming events to /calendar page

### ISSUE THREAD

**Issue by theecrit** [openoakland/openoakland.org#99]
### Description
It's traditionally been a challenge to build attendance for upcoming events like NDoCH, when there's no visibility on the website. Let's at least add 9/22's guest speaker:

> **Tues., Sept. 22, 2020: Darlene Flynn, Director of Race and Equity for the City of Oakland**
> Join us on 9/22 for a special guest speaker: Darlene Flynn, Director of Race and Equity for the City of Oakland. Darlene will share about how her team integrates a racial equity lens to the city’s work using their equity analysis framework. We’ll follow her presentation with a short Q&A, and then host a brief chat to reflect on how we might apply some of these principles to our work at OpenOakland.
>
> For the time being our meetings are fully remote. Register for our weekly Zoom meeting: http://oakca.us/hack-night

> *Schedule:*
> 6:30-6:45 - Announcements and intros
> 6:45-7:05 - Special guest: Darlene Flynn, Director of Race & Equity for the City of Oakland
> 7:05-7:15 - Q&A
> 7:15-7:30 - Reflections on Darlene’s presentation (optional)
> 7:15-9:00 - Project working groups (Slack)

#### If you are working on this issue, consider the following ongoing issues:
- [ ] "Purify" Jekyll source files. Make the file you're working on all markdown, or all HTML, and not both.

**Comment by kwonangela7** [comment]
I'd like to take that issue!
